import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseBoardRepository } from './generated/BaseBoardRepository.js'

/**
 * Repository for interacting with Board entities
 * This class was generated by the Kinotic CLI
 */
export class BoardRepository extends BaseBoardRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
