import { type IEntitiesRepository } from '@kinotic-ai/persistence'
import { BaseTagRepository } from './generated/BaseTagRepository.js'

/**
 * Repository for interacting with Tag entities
 * This class was generated by the Kinotic CLI
 */
export class TagRepository extends BaseTagRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

}
