import { type IEntitiesRepository, Query } from '@kinotic-ai/persistence'
import { BaseTaskRepository } from './generated/BaseTaskRepository.js'

/**
 * Repository for interacting with Task entities
 * This class was generated by the Kinotic CLI
 */
export class TaskRepository extends BaseTaskRepository {

  constructor(entitiesRepository?: IEntitiesRepository) {
    super(false, entitiesRepository)
  }

  /** Number of tasks on a board in a given status. */
  @Query('SELECT COUNT(*) FROM Task WHERE boardId = :boardId AND status = :status')
  countByBoardAndStatus(boardId: string, status: string): Promise<number> {
    /** Autogenerated code, changes will be overwritten. **/
    const parameters = [
      {key: 'boardId', value: boardId},
      {key: 'status', value: status}
    ]
    return this.namedQuery('countByBoardAndStatus', parameters)
  }

}
