import { Entity, AutoGeneratedId, NotNull, Text, Precision, PrecisionType, MultiTenancyType } from '@kinotic-ai/persistence'

/**
 * A Board is a neon-accented lane that groups Tasks — a project, a context, a
 * "today". Every Task belongs to exactly one Board.
 */
@Entity(MultiTenancyType.NONE)
export class Board {

    @AutoGeneratedId
    id: string | null = null

    @NotNull
    @Text
    name: string = ''

    @Text
    description: string = ''

    /**
     * Neon accent key the UI maps to a glow colour.
     * One of: aqua | magenta | lime | azure | amber | rose.
     */
    @NotNull
    accent: string = 'aqua'

    /** Manual sort key among boards; lower sorts first. */
    @Precision(PrecisionType.DOUBLE)
    position: number = 0

    archived: boolean = false

    /** Epoch millis. */
    @Precision(PrecisionType.LONG)
    createdAt: number = 0

    /** Epoch millis. */
    @Precision(PrecisionType.LONG)
    updatedAt: number = 0
}
