import { Entity, AutoGeneratedId, NotNull, Text, Precision, PrecisionType, MultiTenancyType } from '@kinotic-ai/persistence'

/**
 * A reusable neon label that can be attached to any number of {@link Task}s.
 */
@Entity(MultiTenancyType.NONE)
export class Tag {

    @AutoGeneratedId
    id: string | null = null

    @NotNull
    @Text
    name: string = ''

    /**
     * Neon colour key the UI maps to a glow colour.
     * One of: aqua | magenta | lime | azure | amber | rose.
     */
    @NotNull
    color: string = 'aqua'

    /** Epoch millis. */
    @Precision(PrecisionType.LONG)
    createdAt: number = 0

    /** Epoch millis. */
    @Precision(PrecisionType.LONG)
    updatedAt: number = 0
}
