import { Entity, AutoGeneratedId, NotNull, Text, Precision, PrecisionType, MultiTenancyType } from '@kinotic-ai/persistence'

/**
 * A single unit of work on a {@link Board}.
 *
 * `status` moves BACKLOG -> ACTIVE -> DONE. `energy` is Todo Neon's take on
 * priority: how much juice the task needs rather than how urgent it is.
 */
@Entity(MultiTenancyType.NONE)
export class Task {

    @AutoGeneratedId
    id: string | null = null

    @NotNull
    @Text
    title: string = ''

    @Text
    notes: string = ''

    /** Id of the owning {@link Board}. */
    @NotNull
    boardId: string = ''

    /** One of: BACKLOG | ACTIVE | DONE. */
    @NotNull
    status: string = 'BACKLOG'

    /** One of: LOW | MEDIUM | HIGH. */
    @NotNull
    energy: string = 'MEDIUM'

    /** Ids of {@link Tag}s applied to this task. */
    tagIds: string[] = []

    /** Manual sort key within a board/status column; lower sorts first. */
    @Precision(PrecisionType.DOUBLE)
    position: number = 0

    /** Epoch millis, or 0 when no due date is set. */
    @Precision(PrecisionType.LONG)
    dueDate: number = 0

    /** Epoch millis the task was moved to DONE, or 0 while not done. */
    @Precision(PrecisionType.LONG)
    completedAt: number = 0

    /** Epoch millis. */
    @Precision(PrecisionType.LONG)
    createdAt: number = 0

    /** Epoch millis. */
    @Precision(PrecisionType.LONG)
    updatedAt: number = 0
}
